logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG
domain:
 # port: api.dimension.pub/rongmei_account_api_prod
  port: api.dimension.pub/rongmei_account_api_dev
  #port: 127.0.0.1:8080
jwt:
  claimKey:
    username: "username"
    authorities: "authorities"
  secret: "wfhg9hr-1jfpjf-p3j-=vgf0pvmo3k=2-3rj0-3j=gn[=3-g[mj"
  header: Authorization
  tokenHead: "Bearer "
oos:
  accessKey: "c4582dec5d0809103126"
  secretKey: "47c783687d4c452c5d71b817b8c481915fb0094a"
  endPoint: "http://oos-bj2.ctyunapi.cn"
  bucketName: "njutakeout"
spring:
  jpa:
    database: mysql
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rongmeimall?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
  aop:
    auto: true
    proxy-target-class: false
  profiles:
    active: dev
alipay:
  app_id: 2021001167692742
  gateway: https://openapi.alipay.com/gateway.do
  sign_type: RSA2
  charset: utf-8