pipeline {
    agent any
    environment {
        ENVIRONMENT_TEST_FLAG = 'NO'
    }
    stages {
        stage('Build') {
            steps {
                sh 'echo Build stage ...'
            }
        }
        stage('Test') {
            steps {
                sh 'echo Test stage ...'
            }
        }
        stage('Deliver for development') {
            when {
                branch 'develop'
            }
            steps {
                sh 'echo develop stage ...'
                sh 'bash develop.sh'
                sh 'echo end develop stage ...'
            }
        }
        stage('Deploy for production') {
            when {
                branch 'master'
            }
            steps {
                sh 'echo production stage ...'
                sh 'bash prod.sh'
                sh 'echo end production stage ...'
            }
        }
    }
}